// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccessService.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAccessService.Models
{
    public partial class BGM_dbContext
    {
        private IBGM_dbContextProcedures _procedures;

        public virtual IBGM_dbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new BGM_dbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IBGM_dbContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<uspLogErrorResult>().HasNoKey().ToView(null);
        }
    }

    public partial class BGM_dbContextProcedures : IBGM_dbContextProcedures
    {
        private readonly BGM_dbContext _context;

        public BGM_dbContextProcedures(BGM_dbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<uspLogErrorResult>> uspLogErrorAsync(OutputParameter<int?> ErrorLogID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrorLogID = new SqlParameter
            {
                ParameterName = "ErrorLogID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = ErrorLogID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterErrorLogID,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<uspLogErrorResult>("EXEC @returnValue = [dbo].[uspLogError] @ErrorLogID OUTPUT", sqlParameters, cancellationToken);

            ErrorLogID.SetValue(parameterErrorLogID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
