// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccessService.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAccessService.Models
{
    public partial interface IBGM_dbContextProcedures
    {
        Task<List<uspLogErrorResult>> uspLogErrorAsync(OutputParameter<int?> ErrorLogID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
