// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessService.Models
{
    public partial class PurchaseOrdersProcessedSent
    {
        public int PurchaseOrderId { get; set; }
        public int PurchaseOrderDetailId { get; set; }
        public bool OrderProcessed { get; set; }
        public bool OrderSent { get; set; }
        public int Channel { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}