// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccessService.Models
{
    public partial class PurchaseOrderSentChannel
    {
        public int PurchaseOrderSentChannelId { get; set; }
        public string Name { get; set; }
        public bool? Active { get; set; }
    }
}